### ISSUE TITLE
Log cluttered with "There was an OPT answer. Not currently handled."

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/jmdns#12]
Since iOS8 became available, the jupnp library spilts out many WARN log messages like

```javax.jmdns.impl.DNSIncoming[:415] - There was an OPT answer. Not currently handled. Option code: 65002 data: 37B7A9593A9A8919```

if there are iOS devices on the same network.

**Comment by Shmixx** [comment]
Kai, I believe the following issue which I've narrowed down to an iOS problem is similarly related as these messages were often (in my implementation) found intermingled with the OPT answer messages. Just wanted to add this here in case it could help in narrowing down either issue any better by connecting them.
https://github.com/openhab/openhab.ios/issues/31

**Comment by albertovm** [comment]
https://github.com/openhab/jmdns/issues/2
