### ISSUE TITLE
JDK 8 compatibility

### ISSUE THREAD

**Issue by beowulfe** [openhab/jmdns#15]
Compiling against the JDK 8 libraries fails due to the return type of of javax.jmdns.impl.DnsCache._EmptyCache.keySet(). The return type was changed from Set<K> to ConcurrentHashMap.KeySetView<K,V>. 

I considered a few fixes, but couldn't come up with a solution that wouldn't either a) break builds against earlier JDK versions or b) introduce a breaking API change.

How strongly do you feel about API compatibility for the impl.* classes?

**Comment by kaikreuzer** [comment]
> How strongly do you feel about API compatibility for the impl.* classes?

I would not consider them to be a part of the public API, so imho it is fine to break compatibility here.
@spearway would you agree?

**Comment by kaikreuzer** [comment]
No answer from @spearway should count as agreement.
So @beowulfe, feel free to create a PR with your changes!
