### ISSUE TITLE
RFC: Legacy Unicast Responses

### ISSUE THREAD

**Issue by maggu2810** [openhab/jmdns#21]
The chapter "Legacy Unicast Responses" of  RFC 6762 (https://tools.ietf.org/html/rfc6762) is not implemented.

If you want to use a very simple mDNS client that could not use multicast sockets you need this feature.

This was already report in the year 2011 on the sourceforge bug tracker: http://sourceforge.net/p/jmdns/bugs/117/

**Comment by maggu2810** [comment]
I have started to implement this here: https://github.com/openhab/jmdns/compare/master...maggu2810:unicast-response
Comments are welcome.

**Comment by kaikreuzer** [comment]
Implemented with https://github.com/openhab/jmdns/pull/22
